
config-version: 2
nhl_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: "ACCOUNTADMIN"
      database: "NHL_ELT"
      warehouse: "NHL_ELT"
      schema: "DEV"
      threads: 4
      client_session_keep_alive: False